FROM php7.1.0
RUN composer global require "squizlabs/php_codesniffer=*"
RUN composer global require phpmd/phpmd
RUN composer global require "sebastian/phpcpd=*"
RUN composer global require phpunit/phpunit