FROM php5.6.29
RUN composer global require "squizlabs/php_codesniffer=*"
RUN composer global require phpmd/phpmd
RUN composer global require "sebastian/phpcpd=*"
RUN composer global require phpunit/phpunit