version: '2'

services:
  php-fpm:
    image: skiplee/php:7-fpm
    volumes:
      - /www:/www
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./conf/php.ini-development:/usr/local/etc/php/php.ini
      - ./conf/php.ini-production:/usr/local/etc/php/php.ini

  openresty:
    image: openresty/openresty:alpine
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/vhost:/usr/local/openresty/nginx/conf/vhost
      - /data/openresty/logs:/usr/local/openresty/nginx/logs
    volumes_from:
      - php-fpm
    links:
      - php-fpm
    ports:
      - 80-89:80-89

networks:
  default:
    external:
      name: network_default
