version: '2'
services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./conf.d/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - /data/atlassian/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  confluence:
    image: skiplee/confluence:6.6
    depends_on:
      - mysql
    volumes:
      - /data/atlassian/confluence:/var/atlassian/application-data/confluence
    ports:
      - "8090:8090"
    restart: always
  
  jira:
    image: skiplee/jira:7.7.1
    depends_on:
      - mysql
    volumes:
      - /data/atlassian/jira:/var/atlassian/application-data/jira
    ports:
      - "8080:8080"
    restart: always
